export const ENDPOINTS = {
  login: 'login',
  check: 'check',
  register: 'register',
  forgotPassword: 'forgot-password',
  resetPassword: 'reset-password',
  history: 'history',
  payments: 'payments',
  image: 'image',
  generate: 'generate',
  plans: 'plans',
  purchase: 'purchase',
  faq: 'faq',
  profile: 'profile',
  email: 'email',
  verify: 'verify',
  policy: 'privacy_policy',
  terms: 'terms',
  download: 'download',
};
